### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by shahinghasemi** [yellajaswanth/MGATRx#2]
Hello, thanks for your great work. I have got a question: How did you split your drug-disease interactions(1s) and nonInteractions(0s) for the training and testing phase? I can imagine 2 possible approaches: 
- Pick the same amount of nonInteractions as interactions, in otherwords we have 8957 interactions and 8957 non interactions
- use all the nonInteractions for both training and testing

Thanks in advance.

**Comment by yellajaswanth** [comment]
Hi,

Yes, the interactions and non-interactions are split in train, test, and validation sets. 

Lines 258 - 312 in [https://github.com/yellajaswanth/MGATRx/blob/master/MGATRx.py](url) has the split details along with K-Fold setup. 

Thanks
